#!/bin/bash

echo "🚀 Deploying Scrum Poker Frontend to Railway"
echo "==========================================="
echo ""
echo "This script will help you deploy the frontend as a separate service."
echo ""
echo "Steps:"
echo "1. Go to https://railway.app/dashboard"
echo "2. Click on your 'scrum-poker' project"
echo "3. Click '+ New' → 'Empty Service'"
echo "4. Name it 'frontend'"
echo "5. Then run this command in the frontend directory:"
echo ""
echo "   cd frontend && railway link && railway up"
echo ""
echo "Or use GitHub:"
echo "1. Push your code to GitHub"
echo "2. In Railway, click '+ New' → 'GitHub Repo'"
echo "3. Select your repo and set root directory to '/frontend'"
echo ""
echo "Your backend is already live at:"
echo "https://scrum-poker-production.up.railway.app" 