[build]
builder = "nixpacks"
buildCommand = "./gradlew build -x test"

[deploy]
startCommand = "java -jar build/libs/scrum-poker-backend-0.0.1-SNAPSHOT.jar"

[variables]
JAVA_OPTS = "-Xmx512m -Xms256m"
PORT = "8080" 